spring.application.name=beca-alimentos
spring.profiles.active=${SPRING_PROFILE:dev}
server.port=8080
server.servlet.context-path=/api/v1

# Configuración de la base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

